# These are supported funding model platforms

github: rajeshkumarjogi
patreon: rajeshkumarjogi
open_collective:           # Leave blank if not used
ko_fi: rajeshkumarjogi
tidelift:                  # Leave blank unless registered on Tidelift
community_bridge:          # Leave blank if not applicable
liberapay:                 # Optional: add username if used
issuehunt:                 # Optional: if your repo is listed on IssueHunt
lfx_crowdfunding:          # Optional: only if listed
polar:                     # Optional: if you're using Polar.sh
buy_me_a_coffee: rajeshkumaw
thanks_dev:                # Optional
custom: ['https://www.buymeacoffee.com/rajeshkumarjogi', 'https://github.com/sponsors/jogi-rajeshkumar']
